package frist_Program;

import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

public class seleniumAutomation {
	public static void main (String[]args) throws InterruptedException{
		System.out.println("project folder" + System.getProperty("user.dir"));
		System.setProperty("webDriver.chrome.driver", System.getProperty("user.dir")+"//Drivers//chrome.exe");
		WebDriver driver=new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://demo.automationtesting.in/Register.html");System.out.println("Register Opened:-");
		driver.findElement(By.xpath("//input[@placeholder=\"First Name\"]")).sendKeys("Srikar");System.out.println("Fname Printed");Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@placeholder=\"First Name\"]")).clear();System.out.println("fname cleared");Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@placeholder=\"Last Name\"]")).sendKeys("chittipanthula");System.out.println("Lname Printed:-");Thread.sleep(1000);
		driver.findElement(By.xpath("//textarea[@ng-model=\"Adress\"]")).sendKeys("chamalapalli village ");System.out.println("Adress Printed:-");Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@ng-model=\"EmailAdress\"]")).sendKeys("chsrikar2066@gmail.com ");System.out.println("Email printed:-");Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@ng-model=\"Phone\"]")).sendKeys("0000");System.out.println("Ph No printed:-");Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@name=\"radiooptions\"])[1]")).click();System.out.println("male Radio Button  clicked:-");Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@name=\"radiooptions\"])[2]")).click();System.out.println("female Radio Button  clicked:-");Thread.sleep(1000);
		driver.findElement(By.id("checkbox2")).click();System.out.println("checkbox 2 selected");Thread.sleep(1000);
		WebElement Cricket=driver.findElement(By.id("checkbox1"));Cricket.click();System.out.println("Cricket :" +Cricket.isSelected());Thread.sleep(1000);
		driver.findElement(By.id("checkbox3")).click();System.out.println("checkbox 3 selected");Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id=\"firstpassword\"]")).sendKeys("srikare@2500246");System.out.println("password entered");Thread.sleep(1000);
		driver.findElement(By.xpath("//input[@id=\"secondpassword\"]")).sendKeys("srikare@2500246");System.out.println("password confirmed");Thread.sleep(1000);
		driver.findElement(By.name("signup")).click();System.out.println("sign up button clicked");Thread.sleep(1000);
		driver.navigate().to("https://www.facebook.com/");System.out.println("facebook opened:::-" + driver.getTitle());Thread.sleep(1000);
		driver.navigate().back();System.out.println("back to facebook :::-" + driver.getTitle());Thread.sleep(1000);
		driver.navigate().forward();System.out.println("clicked forward:::-" + driver.getTitle());Thread.sleep(1000);
		driver.navigate().refresh();System.out.println("Site was refreshed" + driver.getTitle());Thread.sleep(1000);
		driver.navigate().to("https://demo.automationtesting.in/Register.html");System.out.println(driver.getTitle());Thread.sleep(1000);
		driver.findElement(By.xpath("//a[contains(text(),\"Switch\")]")).click();System.out.println("click to switch");
		driver.findElement(By.xpath("//a[contains(text(),\"Alert\")]")).click();System.out.println("entered to alert");
		driver.findElement(By.xpath("//a[contains(text(),\"Alert with OK\")]")).click();System.out.println("clicked on alert");
		driver.findElement(By.xpath("//button[contains(text(),\"alert box\")]")).click();;System.out.println("alert box");Thread.sleep(1000);
		driver.switchTo().alert().accept();System.out.println("alert accepcted");
		driver.navigate().to("https://demo.automationtesting.in/Register.html");System.out.println(driver.getTitle());Thread.sleep(1000);
		driver.findElement(By.xpath("//a[contains(text(),\"Switch\")]")).click();;;System.out.println("click to switch");
		driver.findElement(By.xpath("//a[contains(text(),\"Alert\")]")).click();System.out.println("clicked on alert ");
		driver.findElement(By.xpath("//a[contains(text(),\"Alert with OK & Cancel \")]")).click();System.out.println("clicked on alert with ok");
		driver.findElement(By.xpath("//button[contains(text(),\"confirm box \")]")).click();System.out.println("confirm box");Thread.sleep(1000);
		driver.switchTo().alert().dismiss();System.out.println("alert dismissed");
		driver.navigate().to("https://demo.automationtesting.in/Register.html");System.out.println(driver.getTitle());Thread.sleep(1000);
		driver.findElement(By.xpath("//a[contains(text(),\"Switch\")]")).click();;;System.out.println("click to switch");
		driver.findElement(By.xpath("//a[contains(text(),\"Alert\")]")).click();System.out.println("clicked on alert ");
		driver.findElement(By.xpath("//a[contains(text(),\"Alert with Textbox \")]")).click();System.out.println("clicked on alert with Textbox");
		driver.findElement(By.xpath("//button[contains(text(),\"prompt box \")]")).click();System.out.println("Promt box");Thread.sleep(1500);
		driver.switchTo().alert().sendKeys("puspha");System.out.println("text enterd into the alert");Thread.sleep(1500);
		driver.switchTo().alert().accept();System.out.println("alert accepcted");
		System.out.println("register form  and alerts are completed");
		driver.get("https://demo.automationtesting.in/Register.html");System.out.println(driver.getTitle());
		WebElement skill=driver.findElement(By.id("Skills"));
		Select skillset = new Select(skill);System.out.println("skills will be selected");
		skillset.selectByIndex(2);Thread.sleep(1000);
		skillset.selectByIndex(3);Thread.sleep(1000);
		skillset.selectByValue("Android");Thread.sleep(1000);
		skillset.selectByValue("AutoCAD");Thread.sleep(1000);System.out.println("country dropdown in console");
		WebElement country=driver.findElement(By.id("country"));
		Select countydrop = new Select(country);
		List<WebElement> countydropOpt=countydrop.getOptions();
		for (WebElement Option : countydropOpt ) {
			System.out.println(Option.getText());
		}System.out.println("selecting country");
		countydrop.selectByIndex(5);
		Thread.sleep(1000);
		countydrop.selectByValue("Japan");
		Thread.sleep(1000);
		countydrop.selectByVisibleText("New Zealand");
		driver.get("https://demo.automationtesting.in/Frames.html");System.out.println(driver.getTitle());
		driver.switchTo().frame("SingleFrame");System.out.println("entered into single frame");Thread.sleep(1000);
		driver.findElement(By.xpath("(//input[@type=\"text\"])[1]")).sendKeys("srikar");System.out.println("text into single frame");Thread.sleep(1000);
		driver.switchTo().parentFrame();System.out.println("switched into parent frame");
		driver.findElement(By.xpath("//a[contains(text(),\" an Iframe\")]")).click();
		driver.switchTo().frame(driver.findElement(By.xpath("//iframe[@src=\"MultipleFrames.html\"]")));
		driver.switchTo().frame(driver.findElement(By.xpath("//iframe[@src=\"SingleFrame.html\"]"))); 
		driver.findElement(By.xpath("(//input[@type=\"text\"])[1]")).sendKeys("chittipanthula");System.out.println("text into multi frame");
		driver.switchTo().parentFrame();System.out.println("switched into parent frame");
		ChromeOptions options = new ChromeOptions();
		options.addArguments("headless");System.out.println("opening headless");
		WebDriver driver5 = new ChromeDriver(options);
		driver.get("https://www.amazon.in/");System.out.println("opened amazon");
		System.out.println("famazon opened by headless");
		System.out.println("title ::: "+ driver5.getTitle());
		driver.get("https://demo.automationtesting.in/Static.html");System.out.println(driver.getTitle());
		Actions actions=new Actions(driver);
		WebElement soc=driver.findElement(By.xpath("//img[@src=\"selenium.png\"]"));
		WebElement des=driver.findElement(By.xpath("//div[@id=\"droparea\"]"));
		actions.clickAndHold(soc).moveToElement(des).release().build().perform();System.out.println("png selected");System.out.println("pnd moved");
		driver.get("https://demo.automationtesting.in/Register.html");System.out.println(driver.getTitle());
		actions.doubleClick(driver.findElement(By.xpath("//label[contains(text(),\"Full\")]"))).build().perform();
		System.out.println("done");System.out.println("double clicked");
		driver.get("https://demo.automationtesting.in/Register.html");System.out.println("clicking context menu");
		actions.contextClick(driver.findElement(By.xpath("//label[contains(text(),\"Full\")]"))).build().perform();
		driver.manage().window().maximize();
		driver.get("https://demo.automationtesting.in/Register.html");System.out.println(driver.getTitle());
		Actions actions2=new Actions(driver);
		WebElement wd =driver.findElement(By.xpath("//textArea[@ng-model=\"Adress\"]"));
		WebElement fn =driver.findElement(By.xpath("//input[@ng-model=\"FirstName\"]"));
		WebElement ln =driver.findElement(By.xpath("//input[@ng-model=\"LastName\"]"));
		wd.sendKeys("puspha the rule");System.out.println("text entered in to adress");
		actions2.click(wd).keyDown(wd,Keys.CONTROL).sendKeys("a").sendKeys("c").build().perform();System.out.println("text selected");
		actions2.click(fn).keyDown(fn,Keys.CONTROL).sendKeys("v").keyUp(Keys.CONTROL).build().perform();System.out.println("text pasted");
		actions2.click(ln).keyDown(ln,Keys.CONTROL).sendKeys("v").keyUp(Keys.CONTROL).build().perform();System.out.println("text entered in to lastname");
		actions2.click(wd).keyDown(wd,Keys.BACK_SPACE).build().perform();System.out.println("text cleared in adress");
		System.out.println("every element was executed successfully");

	}
}